import type { ShaderMetadata } from "@/shader-lib/types"

export const plasmaBlobMetadata = {
  name: "Plasma Blob",
  slug: "plasma-blob",
  description:
    "Soft colorful metaballs that merge into a glassy plasma field with cursor influence.",
  tags: ["metaballs", "plasma", "blob", "interactive", "background"],
  difficulty: "intermediate",
  author: "shadercn",
  license: "MIT",
  version: "0.1.0",
  component: "PlasmaBlobShader",
  uniforms: [
    {
      name: "speed",
      label: "Speed",
      type: "slider",
      defaultValue: 0.65,
      min: 0,
      max: 3,
      step: 0.05,
      description: "Animation speed multiplier.",
    },
    {
      name: "blobCount",
      label: "Blob Count",
      type: "slider",
      defaultValue: 7,
      min: 1,
      max: 10,
      step: 1,
      description: "Number of moving metaballs.",
    },
    {
      name: "blobSize",
      label: "Blob Size",
      type: "slider",
      defaultValue: 0.28,
      min: 0.08,
      max: 0.75,
      step: 0.01,
      description: "Base radius of each blob.",
    },
    {
      name: "softness",
      label: "Softness",
      type: "slider",
      defaultValue: 1.25,
      min: 0.6,
      max: 2.8,
      step: 0.05,
      description: "Field falloff strength.",
    },
    {
      name: "intensity",
      label: "Intensity",
      type: "slider",
      defaultValue: 1,
      min: 0,
      max: 3,
      step: 0.05,
      description: "Final color intensity.",
    },
  ],
  examples: ['<PlasmaBlobShader blobCount={7} blobSize={0.28} softness={1.25} />'],
  performanceNotes: [
    "Caps the shader loop at ten blobs for predictable cost.",
    "Lower blobCount for small cards or mobile-heavy pages.",
  ],
} satisfies ShaderMetadata

