import type { ShaderExport } from "@/types/shader"

export const metadata = {
  name: "Gradient",
  slug: "gradient",
  description:
    "An animated multi-stop gradient with linear and radial modes, noise blending, and rotation control. Creates smooth flowing color transitions.",
  author: "shadercn",
  version: "1.0.0",
  tags: ["gradient", "color", "animation", "blend", "background"],
  difficulty: "beginner" as const,
  category: "gradient" as const,
  previewImage: "/shaders/gradient-preview.png",
  uniforms: [
    {
      name: "uTime",
      type: "float" as const,
      default: 0,
      min: 0,
      max: 100,
      step: 0.01,
      description: "Time",
      group: "Animation",
    },
    {
      name: "uSpeed",
      type: "float" as const,
      default: 0.3,
      min: 0.0,
      max: 3.0,
      step: 0.01,
      description: "Animation speed",
      group: "Animation",
    },
    {
      name: "uAngle",
      type: "float" as const,
      default: 0.0,
      min: 0.0,
      max: 6.283,
      step: 0.01,
      description: "Gradient angle (radians)",
      group: "Pattern",
    },
    {
      name: "uBlend",
      type: "float" as const,
      default: 0.3,
      min: 0.0,
      max: 1.0,
      step: 0.01,
      description: "Noise blend amount",
      group: "Pattern",
    },
    {
      name: "uScale",
      type: "float" as const,
      default: 1.0,
      min: 0.5,
      max: 3.0,
      step: 0.1,
      description: "Radial scale",
      group: "Pattern",
    },
    {
      name: "uColor1",
      type: "color" as const,
      default: [0.1, 0.0, 0.2],
      description: "Color 1",
      group: "Colors",
    },
    {
      name: "uColor2",
      type: "color" as const,
      default: [0.5, 0.0, 0.3],
      description: "Color 2",
      group: "Colors",
    },
    {
      name: "uColor3",
      type: "color" as const,
      default: [0.8, 0.2, 0.2],
      description: "Color 3",
      group: "Colors",
    },
    {
      name: "uColor4",
      type: "color" as const,
      default: [0.9, 0.6, 0.1],
      description: "Color 4",
      group: "Colors",
    },
  ],
  license: "MIT",
  createdAt: "2025-01-01",
  updatedAt: "2025-01-01",
  relatedShaders: ["aurora", "noise", "galaxy"],
}

export { default as fragmentShader } from "./fragment.glsl"
export { default as vertexShader } from "./vertex.glsl"

export const defaultUniforms = {
  uTime: 0,
  uSpeed: 0.3,
  uAngle: 0.0,
  uBlend: 0.3,
  uScale: 1.0,
  uColor1: [0.1, 0.0, 0.2],
  uColor2: [0.5, 0.0, 0.3],
  uColor3: [0.8, 0.2, 0.2],
  uColor4: [0.9, 0.6, 0.1],
}
