import type { ShaderMetadata } from "../types"

export const gradientMetadata: ShaderMetadata = {
  name: "Gradient",
  slug: "gradient",
  description: "Smooth animated gradient with noise-based distortion and mouse interaction",
  tags: ["gradient", "noise", "animated", "color"],
  difficulty: "beginner",
  author: "shadercn",
  license: "MIT",
  version: "1.0.0",
  component: "GradientShader",
  uniforms: [
    {
      name: "color1",
      label: "Color 1",
      type: "color",
      defaultValue: "#5227ff",
      description: "First gradient color",
    },
    {
      name: "color2",
      label: "Color 2",
      type: "color",
      defaultValue: "#dbba95",
      description: "Second gradient color",
    },
    {
      name: "color3",
      label: "Color 3",
      type: "color",
      defaultValue: "#d0bce1",
      description: "Third gradient color",
    },
    {
      name: "speed",
      label: "Speed",
      type: "slider",
      defaultValue: 0.4,
      min: 0.1,
      max: 2.0,
      step: 0.1,
      description: "Animation speed",
    },
    {
      name: "noiseDensity",
      label: "Noise Density",
      type: "slider",
      defaultValue: 5.5,
      min: 1.0,
      max: 15.0,
      step: 0.5,
      description: "Density of noise distortion",
    },
    {
      name: "noiseStrength",
      label: "Noise Strength",
      type: "slider",
      defaultValue: 4.0,
      min: 0.5,
      max: 10.0,
      step: 0.5,
      description: "Strength of noise distortion",
    },
  ],
  examples: [
    '<GradientShader color1="#5227ff" color2="#dbba95" color3="#d0bce1" />',
    '<GradientShader speed={0.8} noiseDensity={8} />',
  ],
  performanceNotes: [
    "Uses simplex noise for distortion",
    "Optimized with early exits",
    "Supports reduced motion preferences",
  ],
}
