import type { ShaderExport } from "@/types/shader"

export const metadata = {
  name: "Noise",
  slug: "noise",
  description:
    "Animated fractal noise with domain warping. Creates organic, cloud-like textures using layered fbm noise with octave control.",
  author: "shadercn",
  version: "1.0.0",
  tags: ["noise", "fractal", "fbm", "cloud", "texture", "domain-warping"],
  difficulty: "beginner" as const,
  category: "noise" as const,
  previewImage: "/shaders/noise-preview.png",
  uniforms: [
    {
      name: "uTime",
      type: "float" as const,
      default: 0,
      min: 0,
      max: 100,
      step: 0.01,
      description: "Time",
      group: "Animation",
    },
    {
      name: "uSpeed",
      type: "float" as const,
      default: 0.3,
      min: 0.0,
      max: 2.0,
      step: 0.01,
      description: "Animation speed",
      group: "Animation",
    },
    {
      name: "uScale",
      type: "float" as const,
      default: 3.0,
      min: 0.5,
      max: 10.0,
      step: 0.1,
      description: "Noise scale",
      group: "Pattern",
    },
    {
      name: "uIntensity",
      type: "float" as const,
      default: 1.0,
      min: 0.0,
      max: 2.0,
      step: 0.01,
      description: "Noise intensity",
      group: "Pattern",
    },
    {
      name: "uOctaves",
      type: "int" as const,
      default: 5,
      min: 1,
      max: 8,
      step: 1,
      description: "FBM octaves",
      group: "Pattern",
    },
    {
      name: "uContrast",
      type: "float" as const,
      default: 1.5,
      min: 0.5,
      max: 5.0,
      step: 0.1,
      description: "Contrast",
      group: "Appearance",
    },
    {
      name: "uColor1",
      type: "color" as const,
      default: [0.0, 0.0, 0.0],
      description: "Dark color",
      group: "Colors",
    },
    {
      name: "uColor2",
      type: "color" as const,
      default: [1.0, 1.0, 1.0],
      description: "Light color",
      group: "Colors",
    },
  ],
  license: "MIT",
  createdAt: "2025-01-01",
  updatedAt: "2025-01-01",
  relatedShaders: ["aurora", "water", "gradient"],
}

export { default as fragmentShader } from "./fragment.glsl"
export { default as vertexShader } from "./vertex.glsl"

export const defaultUniforms = {
  uTime: 0,
  uSpeed: 0.3,
  uScale: 3.0,
  uIntensity: 1.0,
  uOctaves: 5,
  uContrast: 1.5,
  uColor1: [0.0, 0.0, 0.0],
  uColor2: [1.0, 1.0, 1.0],
}
