import type { ShaderMetadata } from "../types"

export const cosmicMetadata: ShaderMetadata = {
  name: "Cosmic",
  slug: "cosmic",
  description: "Holographic gradient with cosmic interference patterns and iridescent effects",
  tags: ["cosmic", "holographic", "iridescent", "animated"],
  difficulty: "intermediate",
  author: "shadercn",
  license: "MIT",
  version: "1.0.0",
  component: "CosmicShader",
  uniforms: [
    {
      name: "color1",
      label: "Color 1",
      type: "color",
      defaultValue: "#5227ff",
      description: "First cosmic color",
    },
    {
      name: "color2",
      label: "Color 2",
      type: "color",
      defaultValue: "#dbba95",
      description: "Second cosmic color",
    },
    {
      name: "color3",
      label: "Color 3",
      type: "color",
      defaultValue: "#d0bce1",
      description: "Third cosmic color",
    },
    {
      name: "speed",
      label: "Speed",
      type: "slider",
      defaultValue: 0.4,
      min: 0.1,
      max: 2.0,
      step: 0.1,
      description: "Animation speed",
    },
    {
      name: "noiseDensity",
      label: "Noise Density",
      type: "slider",
      defaultValue: 5.5,
      min: 1.0,
      max: 15.0,
      step: 0.5,
      description: "Density of cosmic noise",
    },
    {
      name: "noiseStrength",
      label: "Noise Strength",
      type: "slider",
      defaultValue: 4.0,
      min: 0.5,
      max: 10.0,
      step: 0.5,
      description: "Strength of cosmic distortion",
    },
    {
      name: "holographicIntensity",
      label: "Holographic Intensity",
      type: "slider",
      defaultValue: 1.0,
      min: 0.0,
      max: 2.0,
      step: 0.1,
      description: "Intensity of holographic effects",
    },
  ],
  examples: [
    '<CosmicShader color1="#5227ff" color2="#dbba95" color3="#d0bce1" />',
    '<CosmicShader holographicIntensity={1.5} speed={0.6} />',
  ],
  performanceNotes: [
    "Uses multiple noise layers for depth",
    "Holographic patterns computed in fragment shader",
    "Supports reduced motion preferences",
  ],
}
