import type { ShaderMetadata } from "@/shader-lib/types"

export const neonVeilMetadata = {
  name: "Neon Veil",
  slug: "neon-veil",
  description:
    "Layered luminous ribbons with a soft cursor drift, built for premium dark hero sections.",
  tags: ["veil", "ribbons", "hero", "noise", "interactive"],
  difficulty: "intermediate",
  author: "shadercn",
  license: "MIT",
  version: "0.1.0",
  component: "NeonVeilShader",
  uniforms: [
    {
      name: "speed",
      label: "Speed",
      type: "slider",
      defaultValue: 0.45,
      min: 0,
      max: 3,
      step: 0.05,
      description: "Animation speed multiplier.",
    },
    {
      name: "intensity",
      label: "Intensity",
      type: "slider",
      defaultValue: 1,
      min: 0,
      max: 3,
      step: 0.05,
      description: "Overall light strength.",
    },
    {
      name: "density",
      label: "Density",
      type: "slider",
      defaultValue: 7.5,
      min: 2,
      max: 16,
      step: 0.25,
      description: "Number of visible ribbon folds.",
    },
    {
      name: "veilOpacity",
      label: "Opacity",
      type: "slider",
      defaultValue: 0.95,
      min: 0,
      max: 1,
      step: 0.05,
      description: "Final alpha multiplier.",
    },
    {
      name: "color1",
      label: "Color 1",
      type: "color",
      defaultValue: "#00F5D4",
      description: "Cool ribbon color.",
    },
    {
      name: "color2",
      label: "Color 2",
      type: "color",
      defaultValue: "#7C3AED",
      description: "Mid ribbon color.",
    },
    {
      name: "color3",
      label: "Color 3",
      type: "color",
      defaultValue: "#F15BB5",
      description: "Hot highlight color.",
    },
  ],
  examples: [
    '<NeonVeilShader speed={0.45} density={7.5} color1="#00F5D4" color2="#7C3AED" color3="#F15BB5" />',
  ],
  performanceNotes: [
    "Uses a single full-screen pass with five ribbon layers.",
    "Best for large backgrounds or contained previews.",
  ],
} satisfies ShaderMetadata

