import type { ShaderMetadata } from "../types"

export const glassMetadata: ShaderMetadata = {
  name: "Glass",
  slug: "glass",
  description: "Transparent glass effect with refraction, Fresnel, and chromatic aberration",
  tags: ["glass", "transparent", "refraction", "fresnel"],
  difficulty: "advanced",
  author: "shadercn",
  license: "MIT",
  version: "1.0.0",
  component: "GlassShader",
  uniforms: [
    {
      name: "color1",
      label: "Color 1",
      type: "color",
      defaultValue: "#67E8F9",
      description: "First glass color",
    },
    {
      name: "color2",
      label: "Color 2",
      type: "color",
      defaultValue: "#F0ABFC",
      description: "Second glass color",
    },
    {
      name: "color3",
      label: "Color 3",
      type: "color",
      defaultValue: "#FCD34D",
      description: "Third glass color",
    },
    {
      name: "speed",
      label: "Speed",
      type: "slider",
      defaultValue: 0.3,
      min: 0.1,
      max: 2.0,
      step: 0.1,
      description: "Animation speed",
    },
    {
      name: "transparency",
      label: "Transparency",
      type: "slider",
      defaultValue: 0.3,
      min: 0.0,
      max: 1.0,
      step: 0.1,
      description: "Glass transparency level",
    },
    {
      name: "refraction",
      label: "Refraction",
      type: "slider",
      defaultValue: 1.5,
      min: 1.0,
      max: 2.5,
      step: 0.1,
      description: "Index of refraction",
    },
    {
      name: "chromaticAberration",
      label: "Chromatic Aberration",
      type: "slider",
      defaultValue: 0.1,
      min: 0.0,
      max: 0.5,
      step: 0.05,
      description: "Chromatic aberration strength",
    },
    {
      name: "fresnelPower",
      label: "Fresnel Power",
      type: "slider",
      defaultValue: 3.0,
      min: 1.0,
      max: 10.0,
      step: 0.5,
      description: "Fresnel effect intensity",
    },
  ],
  examples: [
    '<GlassShader color1="#67E8F9" color2="#F0ABFC" color3="#FCD34D" />',
    '<GlassShader transparency={0.2} refraction={1.8} fresnelPower={5} />',
  ],
  performanceNotes: [
    "Uses simplex noise for distortion",
    "Fresnel calculation per fragment",
    "Supports reduced motion preferences",
  ],
}
